[package]
name = "colors"
version = "0.1.0"
authors = ["Peter Farr <Peter@PrismaPhonic.com>"]
edition = "2018"

[dependencies]
magick_rust = { git = "https://github.com/PrismaPhonic/magick-rust.git" }
regex = "1.1.0"
termcolor = "1.0.4"
